# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["NZSL_ONLINE_SECRET_KEY_BASE"] %>
  s3_bucket:  <%= ENV['S3_BUCKET'] %>
  s3_bucket_url:    <%= ENV['S3_BUCKET_URL'] %>
  aws_access_key_id:  <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
test:
  secret_key_base: <%= ENV["NZSL_ONLINE_SECRET_KEY_BASE"] %>
staging:
  secret_key_base: <%= ENV["NZSL_ONLINE_SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["NZSL_ONLINE_SECRET_KEY_BASE"] %>
